### ISSUE TITLE
Update dependencies to Backbone.Marionette's latest ranges

### ISSUE THREAD

**Issue by ianmstew** [Squareknot/marionette.state#17]

**Comment by ianmstew** [comment]
Fixed by feda8fa1e09bffa159d374a3b5ed75747682b1b9

**Comment by bnjmnhndrsn** [comment]
It looks like the NPM registry hasn't been updated, because when installing from it, I'm still getting the old ranges.

Thanks for all the work, by the way! Very excited to start using this in our app.

**Comment by ianmstew** [comment]
I'll look into it!  Sorry for the delay--hit a job transition, now I'm back in business.

**Comment by ianmstew** [comment]
`v0.4.1`, just published, includes the latest dependencies.
